Repository oracc/nisaba, pull requests merged in 2022-10, with the labels that each got.

#119 Allow multiple texts from same project in one file
  CHANGELOG.md
  src/atf_model.ts
  src/test/suite/atf.test.ts
  src/test/suite/input/na-archival.atf
  src/test/suite/input/two_projects.atf
Labels: remote

#123 Add documentation for glossaries and remote files
  docs/about.md
  docs/development.md
  docs/remote-files.md
  docs/user_guide.md
  docs/working-with-glo-files.md
Labels: documentation, remote

#127 Update Node.js version in CI
  .github/workflows/ci.yml
Labels: testing, technical
